# -*- coding: utf-8 -*-
"""SimplifiedEval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_16Jw_MPmz3fw_TCK7f0mDv9CywEYOEG

Please note that the comments which explain the code of simplifiedeval are generated by ChatGPT.
"""

# TODO fix
# from google.colab import drive
# drive.mount('/content/drive')

# !pip install datasets
import datasets  # noqa  # check if datasets is installed

import simplifiedeval.probe_training.gpu_playground  # noqa  # import will execute code in it's current state

import simplifiedeval.probe_training.cpu_playground  # noqa  # import will execute code in it's current state

import simplifiedeval.probe_training.glove_cpu_playground  # noqa  # import will execute code in it's current state

import simplifiedeval.probe_training.glove_gpu_playground  # noqa  # import will execute code in it's current state

import simplifiedeval.test_preds_to_csv  # noqa  # import will execute code in it's current state

import simplifiedeval.csvs_to_dictionary  # noqa  # import will execute code in it's current state
