# -*- coding: utf-8 -*-
"""SimplifiedEval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_16Jw_MPmz3fw_TCK7f0mDv9CywEYOEG

Please note that the comments which explain the code of simplifiedeval are generated by ChatGPT.
"""
from dotenv import load_dotenv, find_dotenv


def main():
    import environment

    environment.verify()
    DEVELOP_MODE = environment.get_flag("DEVELOP_MODE")

    import logging

    logger = logging.getLogger("src.simplifiedeval")

    logger.info("Starting simplifiedeval")
    if DEVELOP_MODE:
        logger.warning("DEVELOP_MODE is enabled")
        # raise RuntimeError("Running with DEVELOP_MODE is not supported anymore")  # TODO comment in

    import src.simplifiedeval.probe_training.gpu_playground as gpu_playground
    import src.simplifiedeval.probe_training.cpu_playground as cpu_playground
    import src.simplifiedeval.probe_training.glove_cpu_playground as glove_cpu_playground
    import src.simplifiedeval.probe_training.glove_gpu_playground as glove_gpu_playground
    import src.simplifiedeval.test_preds_to_csv as test_preds_to_csv
    import src.simplifiedeval.csvs_to_dictionary as csvs_to_dictionary

    # Constants
    #   For playground scripts
    data_path = os.path.join(os.getcwd(), "data/processed")
    out_path = os.path.join(os.getcwd(), "out/outputs_Hf_shuffle")
    train_hash = "499193892"
    test_hashes = ["336359147", "315634198"]
    layers = ["initial", "middle", "final"]
    playground_scripts_kwargs = dict(
        data_path=data_path, out_path=out_path, train_hash=train_hash, test_hashes=test_hashes, layers=layers
    )
    #   For other scripts
    #       The constant CSV file path for test data
    constant_csv_path = os.path.join(os.getcwd(), "data/processed/generated_eval_dataset_with_mask.csv")
    #       The root data directory
    data_dir = out_path
    other_scripts_kwargs = dict(
        constant_csv_path=constant_csv_path, data_dir=data_dir
    )

    # "Cells"
    gpu_playground.main(**playground_scripts_kwargs)

    cpu_playground.main(**playground_scripts_kwargs)

    glove_cpu_playground.main(**playground_scripts_kwargs)

    glove_gpu_playground.main(**playground_scripts_kwargs)

    test_preds_to_csv.main(**other_scripts_kwargs)

    csvs_to_dictionary.main(**other_scripts_kwargs)


if __name__ == '__main__':
    # find .env automagically by walking up directories until it's found, then
    # load up the .env entries as environment variables
    load_dotenv(find_dotenv())
    import sys
    import os

    sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
    from src.utils.logging import setup_logger

    setup_logger()
    main()
